# Generated by Django 6.0.2 on 2026-02-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djauthij', '0002_otpverifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pending_delete',
        ),
        migrations.AlterField(
            model_name='otpverifications',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
