# Generated by Django 6.0.2 on 2026-03-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djauthij', '0003_remove_customuser_pending_delete_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
